### ISSUE TITLE
clan lineup clan

### ISSUE THREAD

**Issue by Westo48** [Westo48/clash-discord#228]
# clan lineup clan

## description

Return the lineup of the clan in a cleaner fashion, similar to clan warpreference member

Simile adding the option from existing clan lineup command

## tasks
- [x] discord responder function
- [x] adding option to command param
- [x] command option addition
- [x] readme documentation
