### ISSUE TITLE
client user profile

### ISSUE THREAD

**Issue by Westo48** [Westo48/clash-discord#267]
# client user profile

## description

Return user player info

## command overview

- title
    - {user display name} players
- field for each player
    - TH w/ player name, tag, and link
    - hero list w/ lvls
    - pet list w/ lvls
    - clan info
        - not in a clan
        - badge
        - rank in clan
        - clan name
        - clan tag
    - if player not found in clash
        - return player tag & state that player was not found
        - "consider removing player with `client player option:remove`"

## tasks
- [x] **change `user player` to user info**
    - [x] make sure default is user player
- [x] superuser
- [x] admin
- [x] client
- [x] discord responder function
- [x] cog command addition
- [x] readme documentation
