### ISSUE TITLE
Automatically role discord user on player claim and remove

### ISSUE THREAD

**Issue by Westo48** [Westo48/clash-discord#302]
# Automatically role discord user on player claim and remove

## Description

When a player is claimed by or for a user (using client or admin commands) run the re-role process on that user. Only do this if the server automated value is True. Server automated value is False by default (opt-in).

## Commands

- admin server option:"toggle automate"
    - add option for admin server command
    - toggle the server's automated value

## Tasks

- [ ] add "automated" value to server table
    - default False
- [ ] update db server object model and requests
    - to include automated value
- [ ] add toggle_automated query function in db server file
- [ ] add function to db responder
- [ ] add "toggle automate" option to admin server command
- [ ] role user after player claim
    - only if server.automated is true
    - [ ] client player option:claim
    - [ ] client player option:remove
    - [ ] admin player option:claim
    - [ ] admin player option:remove
