### ISSUE TITLE
change dev environment to utilize different bot application

### ISSUE THREAD

**Issue by Westo48** [Westo48/clash-discord#97]
make a new bot application and change dev environment to utilize that instead of using the production bot for dev and production

# tasks
- [x] make testing application
- [ ] update dev data files to utilize new secret key
- [x] invite bot to testing servers
